export const sectorKeywords = {
  "business-presentations": [
    "presentation",
    "pitch",
    "investor",
    "deck",
    "מצגת",
    "משקיעים",
  ],
  "sell-side-advisory": [
    "sell-side",
    "acquisition",
    "exit",
    "due diligence",
    "מכירה",
    "רכישה",
    "אקזיט",
  ],
  "business-consulting": [
    "consulting",
    "strategy",
    "growth",
    "milestones",
    "innovation",
    "ייעוץ",
    "אסטרטגיה",
    "צמיחה",
  ],
  "ongoing-financial-advisory": [
    "advisory",
    "CFO",
    "long-term",
    "partner",
    "budgeting",
    "פיננסי",
    "סמנכ\"ל",
    "תקצוב",
  ],
  "business-plan": [
    "business plan",
    "plan",
    "planning",
    "roadmap",
    "pitch",
    "תכנית עסקית",
  ],
};
